### New Exception

this the new challenge of python

try:
except:
release:
finally: